version: 2
updates:
    # Dependencies for jhipster-dependencies
    - package-ecosystem: 'maven'
      directory: '/jhipster-dependencies'
      schedule:
          interval: 'daily'
      open-pull-requests-limit: 10

    # Dependencies for jhipster-framework
    - package-ecosystem: 'maven'
      directory: '/jhipster-framework'
      schedule:
          interval: 'daily'
      open-pull-requests-limit: 10

    # Dependencies for GitHub Actions
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'daily'
      open-pull-requests-limit: 10
